psp-guides, rn 1.26 & gpay integration page
paycoreio/docs pull request #205
Opened 2020-12-14 18:44 UTC by YuliyaLios

2020-12-16 12:36 UTC, MichaelKuzyk requested changes

2020-12-21 12:23 UTC, MichaelKuzyk reviewed
![image](https://user-images.githubusercontent.com/28463622/102776709-ea012b80-4397-11eb-8783-cd77716ff03c.png)

Шаг верификации (3дс) - объеденить смартфон и сервис эмитента (это страница не наша, а самого эмитента)

2020-12-21 12:23 UTC, MichaelKuzyk commented on docs/integration/payment-methods/google-pay.md
> +                "type":"process-payment-invoice",
Заменить на payment/sale . в атрибуты  вместо всех филдов засунуть "google_pay



{
"data": {
    "type": "sale-operation",
    "attributes": {
        "google_pay":{
                            "apiVersionMinor":0,
                            "apiVersion":2,
                            "paymentMethodData":{
                                "description":"Mastercard **** 1111",
                                "tokenizationData":{
                                    "type":"PAYMENT_GATEWAY",
                                    "token":""
                                        },
                                    "type":"CARD",
                                    "info":{
                                        "cardNetwork":"MASTERCARD",
                                        "cardDetails":"1111"
                                    }
                                }
                            }
        }
    }
}

2020-12-21 12:23 UTC, MichaelKuzyk commented on docs/integration/payment-methods/google-pay.md
> +    !!! example "Request samples"
Resopnses

2020-12-21 17:54 UTC, closed without merging

2020-12-21 17:55 UTC, YuliyaLios commented
Duplicate of #206