add RN 1.35-1.29
paycoreio/docs pull request #216
Opened 2021-02-04 11:37 UTC by YuliyaLios

2021-02-04 13:56 UTC, MichaelKuzyk requested changes

2021-02-04 13:56 UTC, MichaelKuzyk commented on docs/release-notes/index.md
> +* [Payment Gateway updates](v1.35-1.29/#payment-gateway-updates): added fee set for chargebacks to Payment Scheme options and Provider Reference ID parameter to payment flow
Commerce payment services

2021-02-04 13:56 UTC, MichaelKuzyk commented on docs/release-notes/v1.35-1.29.md
> +#### New Commerce schemes' options: added fee set for chargebacks
Commerce payment services

2021-02-04 13:56 UTC, MichaelKuzyk commented on docs/release-notes/v1.35-1.29.md
> +In addition to the already familiar Commerce scheme settings, now we provide the opportunity to configure fees for chargeback procedure. Thus, you can set them up for merchant account and recompense
добавить что только для каточных методов (имеенно платежей).

payment_card
applepay
googlepay
masterpass

2021-02-04 13:56 UTC, MichaelKuzyk commented on docs/release-notes/v1.35-1.29.md
> +If we provide access to the status page during invoice lifetime, we examine cookies, and the user's IP addresses. And after the invoice expiry, the status page becomes inaccessible to any user.
1. На платёжной странице при оплате теперь мы сетим куку пользователю при сабмите платёжной формы.
2. Возврат на станицу статуса с Issuer ACS ?Page?   и перенаправление на ReturnUrl контролиуется по след. правилам безопасности:
а) Для флоу с HPP: при возврате пользователя проверяем наличие и валидность куки. Если есть кука и НЕ валидна - блокируем (подозрение на утечку данных или фишинговые страницы). Если есть кука и ВАЛИДНА или НЕТ куки но совпадают IP адреса (полученный от юзера при самбите формы и текущий при возврате) - НЕ БЛОКИРУЕМ.
б) для флоу БЕЗ HPP (Н2Н): если в апи пробросили browser_info[browser_ip]  формата IPv4 - сверяем его с айпи юзера на возврате с ACS. Если  browser_info[browser_ip]  формата IPv6 или параметр отсутствует - НЕ блокируем.

2021-02-04 13:56 UTC, MichaelKuzyk commented on docs/release-notes/v1.35-1.29.md
> +It may be a bit heartbreaking for long-minded buyers but necessary to prevent fraud actions.
добавить: юзера мы,  но данные ACS ( PaReq, CReq, xid, CAVV etc) - мы обработаем и передадим на эквайера для финализации.

2021-02-04 18:16 UTC, MichaelKuzyk requested changes

2021-02-04 18:16 UTC, MichaelKuzyk commented on docs/release-notes/v1.35-1.29.md
> +    * If the requested cookie is not available or not set, we further check the user address coincidence.
user IP address

2021-02-04 18:16 UTC, MichaelKuzyk commented on docs/release-notes/v1.35-1.29.md
> +    * If validation fails, we block the user redirect.
if we  gained the ACS data, we process them and pass to the acquirer to finalise transaction

2021-02-07 16:24 UTC, dzubchik requested changes
Remove information about cookies and other security mechanics.

2021-02-08 10:48 UTC, MichaelKuzyk approved these changes

2021-02-08 10:56 UTC, dzubchik approved these changes

2021-02-08 10:56 UTC, merged