rewrite payments basics article
paycoreio/docs pull request #223
Opened 2021-02-25 12:52 UTC by YuliyaLios

rewrite payments basics (payment flow + gateway info), update the main page of the Products section

2021-03-01 13:09 UTC, YuliyaLios commented on docs/products/payment-gateway/index.md
> +* **Authorisation** type of transaction is used to identify whether the payment card is valid, and a customer has enough funds. It doesn't include the actual money transfer. Instead, the issuer bank
поменять последовательность auth -->  void --> capture -->  sale --> refund

2021-04-28 16:18 UTC, MichaelKuzyk requested changes

2021-04-28 16:18 UTC, MichaelKuzyk commented on docs/products/payment-gateway/index.md
> +5. The payment gateways are independent of the bank working hours and run around the clock to process a customer's payment no matter the purchase time.
сомнительнный пункт. Банковские рабочие часы - это для кеша через кассу. Банковские процессинги тоже 24/7 работают

2021-04-28 16:18 UTC, MichaelKuzyk commented on docs/products/payment-gateway/index.md
> +6. Finally, using a single gateway, you collect all payments received in one spot and get reports and analysis to increase your income.
профит единой точки и формата данных  не в  "to increase your income"  а в том что не нужно геморится приводить все данные к одной структуре, и соответственно быстрее  и дешевле строится процесс принятия решений на основании аналитики

2021-04-28 16:18 UTC, MichaelKuzyk commented on docs/products/payment-gateway/index.md
> +    The gateway's correct work strongly depends on the payment provider accounts' proper settings. When you begin configuring {{custom.company_name}} payment gateway, you need to choose and set up se
без Card Gate/
Если Тест в н2н будут коннектить, там автоматом предложит заинитить кардгейт.

2021-06-03 12:05 UTC, MichaelKuzyk commented on docs/products/payment-gateway/index.md
> +8. Within a day or a couple of days, the issuing bank transfers funds to the merchant's account.
тут заюзал бы терминологию "клиринг" и/или "банковский день". Типа после окончания банковского дня при клиринге эмитент трансферит бабки эквайеру

2021-06-03 12:38 UTC, MichaelKuzyk commented on docs/products/payment-gateway/index.md
> +- or **make the authorisation** without writing off funds.
авторизация не может быть рядом с прямым процесом и редиректом. 
Что прямой что редирект может быть любым из : auth+void, auth+capture, purchase

2021-06-03 18:11 UTC, MichaelKuzyk approved these changes

2021-06-04 08:12 UTC, merged