add march april rn
paycoreio/docs pull request #247
Opened 2021-05-14 14:29 UTC by YuliyaLios

2021-05-17 13:00 UTC, YuliyaLios commented on docs/release-notes/v1.54-1.65.md
> +                                "amount":null,
amount - float

2021-05-17 13:04 UTC, YuliyaLios commented on docs/release-notes/v1.54-1.65.md
> +                                "merchant_resolution":"INVALID_DETAILS"
"id" - "rrn": -- "amount": - "currency":"USD", -  "status":" -  "merchant_resolution"

2021-05-17 13:09 UTC, YuliyaLios commented on docs/release-notes/v1.44-1.53.md
> +* [Transaction Registration Addon](#transaction-registration-addon): added API endpoints to get data from Transaction registration addon
remove

2021-05-17 13:11 UTC, YuliyaLios commented on docs/release-notes/v1.44-1.53.md
> +We added `partially_charged_back` along with  `partially_refunded` to the payment status list. Both status types are considered final but keep in mind that transaction refund can be requested several
now - final later - non-final

2021-05-17 13:18 UTC, YuliyaLios commented on docs/release-notes/v1.44-1.53.md
> +The verify stage is an integral part of a transaction flow. Despite this, in several cases (for example, payouts through self-service terminals), it's not always possible to examine requisite existen
Requisite verification is an optional part of a transaction flow when the provider supplies this functionality...
but it's not always possible... and we will initiate a payout transaction skipping ...

2021-05-21 07:54 UTC, MichaelKuzyk requested changes

2021-05-21 07:54 UTC, MichaelKuzyk commented on docs/release-notes/v1.54-1.65.md
> +By default, you get information only about the successfully processed parts. And suppose you need to collect more complete data about splitting, including failed to process amounts and provider IDs,
"suppose you need to collect more complete data about splitting" - сплиттинг будет всегда. Это ж в условии про "Успешные" - если сплит был - будет несколько успешных.

С Expose- просто все будут - включая фейловыйе в результате каскадинга и доп данные

2021-05-21 08:54 UTC, YuliyaLios commented on docs/release-notes/v1.54-1.65.md
> +By default, you get information only about the successfully processed parts. And suppose you need to collect more complete data about splitting, including failed to process amounts and provider IDs,
удалили

2021-05-21 08:57 UTC, MichaelKuzyk requested changes

2021-05-21 10:03 UTC, MichaelKuzyk approved these changes

2021-05-21 10:12 UTC, merged