update psp-guides
paycoreio/docs pull request #248
Opened 2021-05-21 16:24 UTC by YuliyaLios

Add:
- PSP Gate
- SDKFinance

Update:
- Skrill
- Stripe
- IboxBank
- Selcom

2021-05-26 23:48 UTC, MichaelKuzyk requested changes

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/alfabank/index.md
> +* Login suffixed with `-api`
откуда инфа что именно суфикс будет?

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/alfabank/index.md
> +Generate the public and private key pair for the digital sign. Save the private and send the public key in Base64 format to your Alfa Bank account manager.
где алгоритм генерации?

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/alfabank/index.md
> +Choose Test Mode for test connection with Alfa Bank.
Тут везде замени на  _Выберите "тест мод" в соответствии  с  типом подключаемого аккаунта._

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/alfabank/index.md
> +Also, choose the *Save Instant Token* option if you plan to use the Alfa Bank account for instant payments and the *Send Customer Data* option if your account has permission to bind client cards.
Инстанты вроде только с C2A  работают ( лучше уточни у ребят). C2A там это урлы с типом SOAP

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/alfabank/index.md
> +Choose Currencies and Features. You can set these parameters according to available currencies and features for your Alfa Bank account, but it's necessary to verify details of the connection with you
Вот это по каджой инструкции какую пишешь, если нет инфы то конкретно по провайдеру и флоу уточнять у Оперов

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/alfabank/index.md
> +Choose Currencies and Features. You can set these parameters according to available currencies and features for your Alfa Bank account, but it's necessary to verify details of the connection with you
в инструкции нужно указывать "какие фичи когда можно ставить"

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/ecommpay/index.md
>  !!! question "Looking for help connecting your ECommPay account?"
нужно подумать о таких страницах. Если мы не генерили данные, то стаб такой должен быть:
- список филдов для подключения - с указанием "запросить их у провайдера"

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/ecommpay/index.md
>  !!! question "Looking for help connecting your ECommPay account?"
и везде на интеграциях без инфы думаю лучше так сделать

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +If you need to connect ApplePay with Ibox Bank, [complete the requirements](https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay_requirements) and get your Apple Merchant
не совсем корректно думаю. Можно без своего эпл мерчанта это делать. 
С нашей стороны - требования дев апи эпла, а от клиента ничего не нужно, айбокс всё даст

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +Toggle the 'Card verification' option if you want to examine card requisites existence in a provider database before payout processing.
это не проверка наличия карты у провайдера, а верификация валидности карты для выплаты

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/paydoo/index.md
> +Toggle the 'Save OCT Token' option if you plan to use Original Credit Transaction flow for card payments. Also, toggle 'Save Instant token' for instant payments use.
"if you plan to use Original Credit Transaction flow for card payments" - OCT токен- юзается для выплат, а не для приёма

2021-05-26 23:48 UTC, MichaelKuzyk commented on docs/connectors/sdkfinance/index.md
> +* your Merchant Login
Думаю в списках нужно только названия полей. "your" и аналоги - лучше не юзать в эунмах

2021-05-27 13:49 UTC, YuliyaLios commented on docs/connectors/alfabank/index.md
> +* Login suffixed with `-api`
Из доки альфабанка (и в пдфке, которую ты скинул)
![image](https://user-images.githubusercontent.com/18050245/119837641-772e4a80-bf0b-11eb-9a2f-e7998f919c48.png)

2021-05-27 13:52 UTC, YuliyaLios commented on docs/connectors/alfabank/index.md
> +Generate the public and private key pair for the digital sign. Save the private and send the public key in Base64 format to your Alfa Bank account manager.
нет его, ссылка на архив ведет на закрытый конфлюенс
![image](https://user-images.githubusercontent.com/18050245/119838200-e146ef80-bf0b-11eb-9062-3e0319472f3d.png)
могу скопировать из соседних статей

2021-05-27 15:09 UTC, YuliyaLios commented on docs/connectors/alfabank/index.md
> +Also, choose the *Save Instant Token* option if you plan to use the Alfa Bank account for instant payments and the *Send Customer Data* option if your account has permission to bind client cards.
нашла задачу по ним и тест-кейс, не вижу упоминаний об ограничениях

2021-05-28 16:54 UTC, YuliyaLios commented on docs/connectors/alfabank/index.md
> +Choose Currencies and Features. You can set these parameters according to available currencies and features for your Alfa Bank account, but it's necessary to verify details of the connection with you
на обсуждение в пн

2021-05-28 16:54 UTC, YuliyaLios commented on docs/connectors/ecommpay/index.md
>  !!! question "Looking for help connecting your ECommPay account?"
и это тоже обсудим отдельно

2021-05-31 09:19 UTC, MichaelKuzyk requested changes

2021-05-31 09:19 UTC, MichaelKuzyk commented on docs/connectors/stripe/index.md
> +Then verify your domain to go live using [the Apple Pay settings in the Dashboard](https://dashboard.stripe.com/account/payments/apple_pay).
указать явно чтото типа "передать нашему аккаунт менеджеру файл для верификации домена и сам домен, в случае если вы исполюзете Корфай ВайтЛейбл"

2021-05-31 09:19 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +!!! tip "Plan to use Google Pay?"
добавить про добавление домена в гугл

2021-05-31 09:19 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +    Specify the Apple Pay Merchant ID and upload files with the certificate (`server.pem`) and the certificate key (`server.key`). And be sure you define `apple_pay` as a feature in the relevant fiel
добавить про верификацию домена (см. комент к страйпу)

2021-05-31 09:19 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +    Specify the Apple Pay Merchant ID and upload files with the certificate (`server.pem`) and the certificate key (`server.key`). And be sure you define `apple_pay` as a feature in the relevant fiel
apple-developer-merchantid-domain-association.txt (может быть без txt  как у страйпа)

2021-05-31 09:19 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +    Specify the Apple Pay Merchant ID and upload files with the certificate (`server.pem`) and the certificate key (`server.key`). And be sure you define `apple_pay` as a feature in the relevant fiel
https://applepay.gradesfixer.com/.well-known/apple-developer-merchantid-domain-association.txt

пример пути куда мы кладём файл.

2021-05-31 09:19 UTC, MichaelKuzyk commented on docs/connectors/iboxbank/index.md
> +    Specify the Apple Pay Merchant ID and upload files with the certificate (`server.pem`) and the certificate key (`server.key`). And be sure you define `apple_pay` as a feature in the relevant fiel
+ добавить в конкорд

2021-05-31 16:05 UTC, YuliyaLios commented on docs/connectors/alfabank/index.md
> +Choose Currencies and Features. You can set these parameters according to available currencies and features for your Alfa Bank account, but it's necessary to verify details of the connection with you
собираем инфу в отдельной задачке

2021-06-01 18:50 UTC, MichaelKuzyk requested changes

2021-06-01 18:50 UTC, MichaelKuzyk commented on docs/connectors/concord/index.md
> +To connect Apple Pay, you may use your own Apple Merchant identifier or request the support team to provide it. You should also share a domain URL and a domain association file for the merchant ID ve
у конкорда не нужно Apple Merchant identifier.  Только домены

2021-06-01 18:50 UTC, MichaelKuzyk commented on docs/connectors/fondy/index.md
> +    You should also share a domain URL and a domain association file for the merchant ID verification with your {{custom.company_name}} account manager.
Везде одинаково про файл и урлы нада. Тут нет про вайт лейбл и не вайтлейбл. то как написано - можно любой домен указать, какой хош.

Вариант (мб чтото с лексикой \ артиклями нужно подправить)
You should also get verified HPP domain. Provide  {{custom.company_name}} HPP URL to the manager of The Apple Developer Account  and  share the Apple Pay verification file ("apple-developer-merchantid-domain-association") with your {{custom.company_name}} account manager. If You want to use White-label domain  -  шото типа согласуй с нашим менеджером.

2021-06-02 09:19 UTC, MichaelKuzyk approved these changes

2021-06-02 09:20 UTC, merged