update cardpay(unlimint) guide
paycoreio/docs pull request #260
Opened 2021-06-14 14:18 UTC by YuliyaLios

2021-06-17 06:34 UTC, MichaelKuzyk requested changes
Кардпей - скриншоты с новым именем и лого нужно сделать.
И за колбек урл уточни у пацанов: прием+ выплаты - можем ли передавать в апи, хотя бы на приеме. Бо тот урл статичен и он только на пейкор подходит. На х2х кардгейт никак низя его

2021-06-17 12:04 UTC, YuliyaLios commented
> Кардпей - скриншоты с новым именем и лого нужно сделать.
ок, тогда ждем релиз ОФТ

> И за колбек урл уточни у пацанов: прием+ выплаты - можем ли передавать в апи, хотя бы на приеме. Бо тот урл статичен и он только на пейкор подходит. На х2х кардгейт никак низя его
По API только Return URL; на кардгейт колбеки не приходят.

2021-07-01 19:08 UTC, MichaelKuzyk approved these changes

2021-07-02 10:00 UTC, MichaelKuzyk approved these changes

2021-07-02 10:00 UTC, MichaelKuzyk approved these changes

2021-07-02 12:53 UTC, merged