add rn november
paycoreio/docs pull request #285
Opened 2021-11-18 15:21 UTC by YuliyaLios

2021-11-18 17:23 UTC, michaelkuzyk requested changes

2021-11-18 17:23 UTC, michaelkuzyk commented on docs/connectors/index.md
> +| <img src="https://static.openfintech.io/payment_providers/paymega/logo.svg?w=90" width="90px"><br>[Paymega.io](paymegaio/) | ✅ | ✅ | EUR, RUB, UAH, USD | ApplePay, Googlepay |
https://static.openfintech.io/payment_providers/paymegaio/logo.svg?w=90

2021-11-18 17:23 UTC, michaelkuzyk commented on docs/connectors/index.md
> +| <img src="https://static.openfintech.io/payment_providers/paymega/logo.svg?w=90" width="90px"><br>[Paymega.io](paymegaio/) | ✅ | ✅ | EUR, RUB, UAH, USD | ApplePay, Googlepay |
по ним би я не писав нічого тут. Вони індивідуально все дають

2021-11-18 17:23 UTC, michaelkuzyk commented on docs/release-notes/index.md
> +* [Card Gateway updates](v1.113-1.121/#card-gateway-updates): added invoice reference ID (`commerce_invoice_reference_id`) to invoice data for use on HPP, updated card gateway user permissions
не треба назва параметра, це підкапотна штука. 
Мерчантам треба лише знати, що є Інвойс, і можна його айдішку показати на хпп. Звертатись до акаунта по внесенню змін до їх дизайну хпп

2021-11-18 17:23 UTC, michaelkuzyk commented on docs/release-notes/v1.113-1.121.md
> +* [Card Gateway updates](#card-gateway-updates): added invoice reference ID (`commerce_invoice_reference_id`) to invoice data for use on HPP, updated card gateway user permissions
аналогічно попередньому

2021-11-18 17:23 UTC, michaelkuzyk commented on docs/release-notes/v1.113-1.121.md
> +We added a new string attribute for the card gateway invoice: `commerce_invoice_reference_id`. It's connected with the payment invoice reference ID that commerce API uses for invoice creation—you may
Лишити останнє речення. Всі підкапотні штуки - ніколи не пишемо клієнтам, так як для них це шум - вони використати це ніяк не зможуть

2021-11-18 17:23 UTC, michaelkuzyk commented on docs/release-notes/v1.113-1.121.md
> +!!! example "Invoice status response samples"
не треба респонси

2021-11-18 17:50 UTC, YuliyaLios commented on docs/connectors/index.md
> +| <img src="https://static.openfintech.io/payment_providers/paymega/logo.svg?w=90" width="90px"><br>[Paymega.io](paymegaio/) | ✅ | ✅ | EUR, RUB, UAH, USD | ApplePay, Googlepay |
ok

2021-11-18 17:50 UTC, YuliyaLios commented on docs/release-notes/v1.113-1.121.md
> +We added a new string attribute for the card gateway invoice: `commerce_invoice_reference_id`. It's connected with the payment invoice reference ID that commerce API uses for invoice creation—you may
+

2021-11-18 17:50 UTC, YuliyaLios commented on docs/release-notes/v1.113-1.121.md
> +We added a new string attribute for the card gateway invoice: `commerce_invoice_reference_id`. It's connected with the payment invoice reference ID that commerce API uses for invoice creation—you may
переписала абзац

2021-11-18 17:50 UTC, YuliyaLios commented on docs/release-notes/v1.113-1.121.md
> +!!! example "Invoice status response samples"
видалила

2021-11-18 17:50 UTC, YuliyaLios commented on docs/release-notes/v1.113-1.121.md
> +* [Card Gateway updates](#card-gateway-updates): added invoice reference ID (`commerce_invoice_reference_id`) to invoice data for use on HPP, updated card gateway user permissions
ок

2021-11-19 10:33 UTC, michaelkuzyk approved these changes

2021-11-19 10:34 UTC, merged